#!/usr/bin/env bash

mkdir -p ./machine_resources_monitoring/logs

VIRTUALIZER_TYPE=$1

cd "$(dirname "$0")" || exit

MACHINE_HEADERS() {
  echo "usr;nice;sys;iowait;soft;date_time" >logs/machine_monitoring-cpu.csv
  echo "used;date_time" >logs/machine_monitoring-disk.csv
  echo "used;cached;buffer;swap-free;date_time" >logs/machine_monitoring-mem.csv
  echo "num_zombies;date_time" >logs/machine_monitoring-zombies.csv
  echo "offline_count;seconds;date_time" >logs/machineHost_server_status.csv
}

VBOX_HEADERS() {
  echo "cpu;mem;vmrss;vsz;threads;swap;date_time" >logs/vbox_monitoring-VBoxSVC.csv
  echo "cpu;mem;vmrss;vsz;threads;swap;date_time" >logs/vbox_monitoring-VBoxHeadless.csv
  echo "cpu;mem;vmrss;vsz;threads;swap;date_time" >logs/vbox_monitoring-VBoxXPCOMIPCD.csv
}

KVM_HEADERS() {
  echo "cpu;mem;vmrss;vsz;threads;swap;date_time" >logs/kvm_Headless_monitoring.csv
  echo "cpu;mem;vsz;rss;threads;swap;date_time" >logs/kvm_libvirtd_service_monitoring.csv
}

XEN_HEADERS() {
  echo "cpu;mem;vmrss;vsz;threads;swap;date_time" >logs/xen_monitoring-xenbus.csv
  echo "cpu;mem;vsz;rss;threads;swap;date_time" >logs/xen_monitoring-oxenstored.csv
}

MACHINE_HEADERS

stap -o logs/fragmentation.csv memory_fragmentation/fragmentation2b.stp &

if [[ "$VIRTUALIZER_TYPE" == "vbox" ]]; then
  VBOX_HEADERS

  processes/monitoring-VBoxXPCOMIPCD.sh &
  processes/monitoring-VBoxHeadless.sh &
  processes/monitoring-VBoxSVC.sh &

elif [[ "$VIRTUALIZER_TYPE" == "kvm" ]]; then
  KVM_HEADERS

  processes/kvmHeadless_monitoring.sh &
  processes/kvm_libvirtd_monitoring.sh &

elif [[ "$VIRTUALIZER_TYPE" == "xen" ]]; then
  XEN_HEADERS

  processes/xen_oxenstored_monitoring.sh &
  processes/xen_xenbus_monitoring.sh &
fi

general_resources/server-down-count.sh "$VIRTUALIZER_TYPE" &

while true; do
  :
  date_time=$(date +%d-%m-%Y-%H:%M:%S)

  source general_resources/monitoring-cpu.sh
  source general_resources/monitoring-disk.sh
  source general_resources/monitoring-mem.sh
  source general_resources/monitoring-zombies.sh

  sleep 1
done
