#!/bin/bash

source ./vbox_functions.sh

#Time method
minutes=0

#Control variables
reboot_count=0

#Reboot types
force=0
soft=0
ssh=0

# FUNCTION=PRINT_USAGE()
# DESCRIPTION:
#  Displays the script's usage information, including available options and their descriptions (works as a helper menu)
function PRINT_USAGE() {
  echo "script usage $(basename "$0")  [-t <integer> minutes] [-m <integer> mb] [-f (forced reboot)] [-s (soft reboot)] [-ssh (ssh reboot)]" >&1
}

if [[ "$1" =~ ^((-{1,2})([Hh]$|[Hh][Ee][Ll][Pp])|)$ ]]; then
  PRINT_USAGE
  exit 0
else
  while [[ $# -gt 0 ]]; do
    opt="$1"
    shift
    current_arg="$1"
    if [[ "$current_arg" =~ ^-{1,2}.* ]]; then
      echo "WARNING: You may have left an argument blank. Double-check your command."
      exit 1
    fi
    case "$opt" in
    "-t" | "--time")
      minutes=$1
      echo "Starting rejuvenation tests | The virtual machine will restart every $minutes minutes"
      shift
      ;;
    "-f" | "--force")
      force=1
      shift
      ;;
    "-s" | "--soft")
      soft=1
      shift
      ;;
    "-ssh" | "--ssh")
      ssh=1
      shift
      ;;
    "-h" | "--help")
      PRINT_USAGE
      exit 0
      ;;
    *)
      echo "ERROR: Invalid option: \"$opt\"" >&2
      PRINT_USAGE
      exit 1
      ;;
    esac
  done
fi

function REBOOT_VM() {
  ((reboot_count++))
  local current_time
  current_time=$(date "+%Y.%m.%d-%H.%M.%S")
  echo "Rebooting VM $current_time - Reboot count: $reboot_count"
  if [ "$soft" -eq 1 ]; then
    GRACEFUL_REBOOT
  fi

  if [ "$ssh" -eq 1 ]; then
    SSH_REBOOT
  fi

  if [ "$force" -eq 1 ]; then
    FORCED_REBOOT
  fi
}

START_VM

./workload.sh &
machine_resources_monitoring/run &

while true; do
  :
  sleep "$minutes"m

  REBOOT_VM
done
